[[commands]]
name = "browser"
description = "otwiera przeglądarkę"
action_type = "launch"
action_value = "firefox"

[[commands]]
name = "bromber"
description = "otwiera przeglądarkę"
action_type = "launch"
action_value = "google-chrome"

[[commands]]
name = "lock"
description = "wysyła klawisze"
action_type = "keystrokes"
action_value = "ctrl+g"
